### ISSUE TITLE
importFromIMGT results in less clones than actual IMGT alignment

### ISSUE THREAD

**Issue by SolaimanR** [milaboratory/mixcr#137] opened 2016-09-06 14:51 UTC
Hey,

i have another IMGT question. I have compared samples aligned by mixcr using the IMGT database (importFromIMGT) and samples that I uploaded directly to the IMGT server for alignment.

Samples aligned on the IMGT server result in several thousand more clonotypes and usually about 20% more productive reads. For instance:

Aligning one TRB sample using mixcr with the local IMGT library I get

837 clones and 150192 sequences.

Same sample aligned on the IMGT server:

8340 clones and 173957 sequences.

I get a similar result when I use the default mixcr library instead of the imported IMGT. 

What might be the reason for this difference? Parameter settings?

Thank you.

**Comment by dbolotin** [comment] 2016-09-13 17:35
Hi,

sorry for late response.

Please try [MiXCR 2.0](https://github.com/milaboratory/mixcr/releases/latest) with new imported [IMGT library](https://github.com/repseqio/library-imgt) as described [here](http://mixcr.readthedocs.io/en/latest/importSegments.html).

If the issue persists, please post here both report files from IMGT and non-IMGT analysis. 

Best.

**Comment by SolaimanR** [comment] 2016-09-20 09:07
Hey, 

thank you. I downloaded MiXCR 2.0 and the IMGT library file as described in your documentation. I put a copy of the library in all mixcr library directories, but no matter what I do I get following error:

```
Exception in thread "main" java.lang.RuntimeException: Can't find library for following library name and species: imgt + hs
	at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:354)
	at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:257)
	at com.milaboratory.mixcr.cli.ActionAlign.go(ActionAlign.java:105)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:147)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:108)
```

Have you had this issue before? Also, how do I specify species and loci, same as the standard mixcr align options?

Thank you.

**Comment by dbolotin** [comment] 2016-09-20 12:26
Please check that you placed imgt library in the correct folder. Run:
```
mixcr -v
```
this will print list of folders where mixcr looks for libraries.

Here is the [docs](http://mixcr.readthedocs.io/en/latest/align.html#command-line-parameters) for `align` action.

Don't specify chain on the alignment stage, use `-c` [filter option](http://mixcr.readthedocs.io/en/latest/align.html#command-line-parameters) on the `exportClones` step instead, like in this [example](http://mixcr.readthedocs.io/en/latest/align.html#command-line-parameters).

We now use term 'chain' instead of loci, as it better describes the meter.

**Comment by DanteBortone** [comment] 2016-10-03 15:24
I had the same java.lang.RuntimeException.  The solution for me was to specify the full name for the library: -b imgt.201631-4.sv1

**Comment by dbolotin** [comment] 2016-10-03 18:07
Hi @DanteBortone, I just checked on my laptop and our servers, mixcr successfully recognise just `imgt` as library name:
```
mixcr align -b imgt test_R1.fastq.gz test_R2.fastq.gz test.vdjca
```
Could you please post here your OS and output of `mixcr -v`, it seems like some OS/system dependent problem.
Thanks!

**Comment by DanteBortone** [comment] 2016-10-03 19:10
Sure, no problem. 

OS is Linux/redhat
Version : 2.6.18
Release : 238.12.1.el5

call:
`mixcr align -b imgt -s hsa -t 8 -r test_log.txt test_R1.fastq.gz test_R2.fastq.gz test.vdjca`

Exception:
```
Exception in thread "main" java.lang.RuntimeException: Can't find library for following library name and species: imgt + has
        at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:354)
        at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:257)
        at com.milaboratory.mixcr.cli.ActionAlign.go(ActionAlign.java:105)
        at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:147)
        at com.milaboratory.mixcr.cli.Main.main(Main.java:108)
```

mixer -v output:
```
MiXCR v2.0 (built Tue Sep 13 12:41:36 EDT 2016; rev=e44326f; branch=release/v2.0)
RepSeq.IO v1.2.0 (rev=6fa1ac7)
MiLib v1.5 (rev=c0def12)
Built-in V/D/J/C library: repseqio.v1.0

Library search path:
- built-in libraries
- /netscr/dbortone/blca/.
- /netscr/dbortone/mixcr/2.0/libraries
- /nas02/home/d/b/dbortone/.mixcr/libraries
```

.json file location:
/nas02/home/d/b/dbortone/.mixcr/libraries/imgt.201631-4.sv1.json

call that works:
`mixcr align -b imgt.201631-4.sv1 -s hsa -t 8 -r test_log.txt test_R1.fastq.gz test_R2.fastq.gz test.vdjca`

The '-s' argument is vestigial from all of the argument iterations I tried to get around the exception.  I can probably remove this but the cluster is busy at the moment.

**Comment by dbolotin** [comment] 2016-10-03 19:49
Thank you very much! I confirm it is a bug.

It emerged because you decompressed imgt.201631-4.sv1.json.gz file (mixcr can read directly from gzipped file). 

As a workaround you can re-download the library as gzipped json and remove imgt.201631-4.sv1.json .

[The fix](https://github.com/repseqio/repseqio/commit/8d735bcee90c521a07be08e877d0239b7d36c2c3) will be included in upcoming 2.0.1 release.

**Comment by DanteBortone** [comment] 2016-10-03 20:05
Thanks Dmitry!

For other mac users:  OS X automatically decompresses the imgt file upon clicking the download link.  I had to right click the link and select 'Download Linked File' to avoid this.

**Comment by DanteBortone** [comment] 2016-10-04 15:09
I got an exception attempting to run with the -b imgt argument and the .gz file:

```
Exception in thread "main" java.lang.RuntimeException: Conflicting aliases imgt -> imgt.201631-4.sv1 / imgt.201631-4.sv1.json
        at io.repseq.core.VDJCLibraryRegistry.tryResolve(VDJCLibraryRegistry.java:388)
        at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:341)
        at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:257)
        at com.milaboratory.mixcr.cli.ActionAlign.go(ActionAlign.java:105)
        at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:147)
        at com.milaboratory.mixcr.cli.Main.main(Main.java:108)
```
The uncompressed version of the imgt file was removed, so that shouldn't be the source of the exception.

**Comment by dbolotin** [comment] 2016-10-05 09:46
This error may be caused by `imgt.201631-4.sv1.json` file in other library search folders:

* folder from which you start mixcr
* mixcr installation folder `/netscr/dbortone/mixcr/2.0/libraries` (according to the output from `mixcr -v` you posted)

Try to remove the file from these folders.

Let me know, if it is not the case.

**Comment by DanteBortone** [comment] 2016-10-05 18:10
Yup, you were right.  I deleted the other .json file. 

The uncompressed .gz file now runs with the `-b imgt ` argument. No errors were produced.

Thanks!

**Closed** 2016-10-12 14:03 UTC
