### ISSUE TITLE
mixcr analyze shotgun

### ISSUE THREAD

**Issue by ibseq** [milaboratory/mixcr#472] opened 2018-12-17 10:52 UTC
## Checklist before submitting the issue:

 - [ ] The issue is strongly related to the MiXCR software
 - [ ] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [ ] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

## Exact MiXCR commands 

*Paste here __exact__ MiXCR commands you used (enclose it with single `` ` ``  for better formatting)*

## MiXCR report files 

*Paste here content of the report files produced by MiXCR (enclose it with triple ```` ``` ````  for better formatting)*

**Comment by PoslavskySV** [comment] 2018-12-17 14:35
closing as the issue is empty

**Closed by PoslavskySV** 2018-12-17 14:35 UTC
