### ISSUE TITLE
Generic-ont alignment problem

### ISSUE THREAD

**Issue by mszelest** [milaboratory/mixcr#1597] opened 2024-03-22 13:27 UTC
I've tried to use my ONT data (I used SQK-LSK109 kit for IGHV sequencing) to analyze data but alignment stops at some point and I don't understand whats wrong?

'mixcr align --report CLL-0895_result.align.report.txt --json-report CLL-0895_result.align.report.json --preset generic-ont --save-output-file-names CLL-0895_result.align.list --dna --species hsa CLL-0895_IGHV.fastq CLL-0895_result.vdjca'

'Running:
mixcr align --report CLL-0895_result.align.report.txt --json-report CLL-0895_result.align.report.json --preset generic-ont --save-output-file-names CLL-0895_result.align.list --dna --species hsa CLL-0895_IGHV.fastq CLL-0895_result.vdjca
Alignment: 0%
Alignment: 3,7%  ETA: 00:52:17
Alignment: 6,1%  ETA: 01:18:15
Alignment: 8,5%  ETA: 01:15:53
Alignment: 11,4%  ETA: 01:01:13
Alignment: 14,3%  ETA: 00:59:36
Alignment: 17,5%  ETA: 00:51:17
Alignment: 20,6%  ETA: 00:52:17
Alignment: 23,3%  ETA: 00:56:35
Alignment: 26,1%  ETA: 00:54:18
Alignment: 28,9%  ETA: 00:49:15
Alignment: 32,6%  ETA: 00:36:43
Alignment: 35,4%  ETA: 00:47:36
Alignment: 38,1%  ETA: 00:45:22
Alignment: 40,7%  ETA: 00:46:16
Alignment: 44,2%  ETA: 00:31:45
Alignment: 47,4%  ETA: 00:32:52
Alignment: 51,1%  ETA: 00:26:36
Alignment: 54%  ETA: 00:31:57
java.lang.AssertionError
	at com.milaboratory.o.bM.a(SourceFile:95)
	at com.milaboratory.o.aX.c(SourceFile:3067)
	at com.milaboratory.o.aX.e(SourceFile:99)
	at com.milaboratory.o.aS.c(SourceFile:41)
	at com.milaboratory.mixcr.cli.CommandAlignPipeline$ProcessingBundle.<init>(SourceFile:464)
	at com.milaboratory.mixcr.cli.CommandAlign$Cmd$createReader$4.invoke(SourceFile:995)
	at com.milaboratory.mixcr.cli.CommandAlign$Cmd$createReader$4.invoke(SourceFile:995)
	at com.milaboratory.o.EO.process(SourceFile:31)
	at cc.redberry.pipe.util.SimpleProcessorWrapper.take(SimpleProcessorWrapper.java:43)
	at com.milaboratory.o.ER.take(SourceFile)
	at cc.redberry.pipe.util.Chunk.readChunk(Chunk.java:78)
	at cc.redberry.pipe.CUtils$2.take(CUtils.java:169)
	at cc.redberry.pipe.CUtils$2.take(CUtils.java:161)
	at cc.redberry.pipe.blocks.O2ITransmitter.run(O2ITransmitter.java:63)
	at java.base/java.lang.Thread.run(Thread.java:832)'

**Comment by mizraelson** [comment] 2024-03-22 15:31
Hi, can you please try the latest MiXCR version and let me know if the issue is still there.

**Comment by mszelest** [comment] 2024-03-22 19:48
Thanks for a quick response! I got this version:
App version: 4.6.0; built=Sat Dec 09 20:48:42 CET 2023; rev=c9fafa41fe; lib=repseqio.v4.0
Isn't it the latest version?

**Comment by mizraelson** [comment] 2024-03-25 06:14
Yes, 4.6 is the latest version so far. It seems the issue lies with the FASTQ quality parsing. Would it be possible for you to share the problematic file?

**Comment by mszelest** [comment] 2024-03-25 07:50
Hi,

Thank you for helping me with this issue. Below I attach a link with the
fastq file.

Kind regards
Monika
 CLL-0895_IGHV.fastq
<https://drive.google.com/file/d/1vv8IPXCADZnjC7vMmVx4JajUTisRXnfU/view?usp=drive_web>

pon., 25 mar 2024 o 07:14 mizraelson ***@***.***> napisał(a):

**Comment by bshim181** [comment] 2024-03-25 19:26
I am facing the same issue and I was wondering if it has been resolved yet.

**Comment by mizraelson** [comment] 2024-04-01 04:58
Hi,
So, the issue is with an unexpectedly long read length. We will fix it and I will reply with a updated version soon.

**Comment by 2003100127** [comment] 2024-04-03 22:56
> Hi, So, the issue is with an unexpectedly long read length. We will fix it and I will reply with a updated version soon.

Thanks, please. I am having the same issue and waiting for your feedback. Or if there is a version to fall back.

**Comment by mizraelson** [comment] 2024-04-29 23:49
Hi, we have added a fix in [the latest develop version](https://link.milaboratory.com/software/mixcr/mixcr-develop.zip). Please try and let me know if it works. I will close this issue for now. Feel free to reopen if needed.

**Closed as completed by mizraelson** 2024-04-29 23:49 UTC
