### ISSUE TITLE
exportAlignments ERROR

### ISSUE THREAD

**Issue by Z-YWJ** [milaboratory/mixcr#1810] opened 2024-10-01 12:33 UTC
Hello, thank for fantastic software. Recently, I meet an error when I try to export reads alignment.

## Data format
my fastq data is PE150 TBCR data.

## This is my code:

`
name=result
mixcr_latest align -Xmx400g -p rna-seq --species hsa -f -OsaveOriginalReads=true --impute-germline-on-export  $file_1.fq.gz $file_2.fq.gz  ${name}.vdjca --report ${name}.align.report.txt ;
mixcr_latest assemble -Xmx500g --write-alignments -f  ${name}.vdjca ${name}.clna --report ${name}.assemble.report.txt
mixcr_latest exportAlignments -Xmx400g -vGene -dGene  -jGene -cGene -cFamily -f -descrsR2 -descrsR1 -cloneId -readIds -targetSequences -topChains -chains -cloneIdWithMappingType ${name}.clna ${name}.exportAlignment.report.tsv
mixcr_latest exportClones --filter-stops --filter-out-of-frames -f -topChains -targets --impute-germline-on-export ${name}.clna ${name}.clones.tsv 

`
When I run 'exportAlignments' command, there is a error, like this:

## ERROR info

`
Exporting alignments: 1.2%  ETA: 02:42:14
Exporting alignments: 2.5%  ETA: 02:30:03
Exporting alignments: 4.1%  ETA: 02:04:19
Exporting alignments: 5.5%  ETA: 02:11:04
Exporting alignments: 7.4%  ETA: 01:35:37
App version: 4.6.0-195-develop; built=Wed May 15 10:10:39 EDT 2024; rev=1a90bc5691; lib=repseqio.v5.0
java.lang.AssertionError: [{false 0 119 120}, {false 1 102 120}, {true 1 68 80}]
[{false 1 101 120}, {true 1 68 80}]
-1
        at com.milaboratory.o.jP.c(SourceFile:524)
        at com.milaboratory.o.EF.a(SourceFile:98)
        at com.milaboratory.o.EF.a(SourceFile:105)
        at com.milaboratory.o.jP.j(SourceFile:356)
        at com.milaboratory.o.un.invoke(SourceFile:1428)
        at com.milaboratory.o.lB.extractValue(SourceFile:57)
        at com.milaboratory.mixcr.export.FieldWithParameters$create$2.invoke(SourceFile:583)
        at com.milaboratory.mixcr.export.FieldWithParameters$create$2.invoke(SourceFile:582)
        at com.milaboratory.o.lK.a(SourceFile:25)
        at com.milaboratory.o.my.put(SourceFile:40)
        at cc.redberry.pipe.CUtils.drain(CUtils.java:82)
        at cc.redberry.pipe.util.PipeExtensionsKt.drainToAndClose(PipeExtensions.kt:155)
        at com.milaboratory.mixcr.cli.CommandExportAlignments$Cmd.run1(SourceFile:169)
        at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run0(SourceFile:69)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-32(SourceFile:538)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.milaboratory.mixcr.cli.Main.execute(SourceFile:105)
        at com.milaboratory.mixcr.cli.Main.main(SourceFile:101)
        Suppressed: java.lang.IllegalStateException: random access primitivI blocks or primitivI reader not closed
                at com.milaboratory.o.Er.a(SourceFile:174)
                at com.milaboratory.o.Er.close(SourceFile:287)
                at com.milaboratory.o.iV.close(SourceFile)
                at com.milaboratory.mixcr.cli.CommandExportAlignments$AlignmentsAndMetaInfo.close(SourceFile)
                at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseable.kt:64)
                at com.milaboratory.mixcr.cli.CommandExportAlignments$Cmd.run1(SourceFile:139)
                ... 13 more
`
Looking forward to your help!!!

**Comment by Z-YWJ** [comment] 2024-10-01 12:34
My mixcr version is 

MiXCR v4.6.0-195-develop (built Wed May 15 10:10:39 EDT 2024; rev=1a90bc5691; branch=develop; host=fv-az1024-873)

**Comment by mizraelson** [comment] 2024-10-01 23:39
Could you please try using the latest available version and let me know if the issue persists?

**Comment by Z-YWJ** [comment] 2024-10-02 05:28
OK, thank you, I will try

**Comment by Z-YWJ** [comment] 2024-10-02 07:46
However, when I try same command and data with **MiXCR v4.7.0 (built Wed Aug 07 15:19:48 EDT 2024; rev=976ba14139; branch=no_branch; host=fv-az1019-185)** 

I still meet the same error, just like 

> Exporting alignments: 0%
Exporting alignments: 1.2%  ETA: 02:40:59
Exporting alignments: 2.4%  ETA: 02:40:14
Exporting alignments: 3.8%  ETA: 02:21:40
Exporting alignments: 5.2%  ETA: 02:13:58
Exporting alignments: 6.8%  ETA: 01:58:35
App version: 4.7.0; built=Wed Aug 07 15:19:48 EDT 2024; rev=976ba14139; lib=repseqio.v5.1
java.lang.AssertionError: [{false 0 119 120}, {false 1 102 120}, {true 1 68 80}][{false 1 101 120}, {true 1 68 80}]
-1
        at com.milaboratory.o.kd.c(SourceFile:524)
        at com.milaboratory.o.EV.a(SourceFile:98)
        at com.milaboratory.o.EV.a(SourceFile:105)
        at com.milaboratory.o.kd.j(SourceFile:356)
        at com.milaboratory.o.uA.invoke(SourceFile:1428)
        at com.milaboratory.o.lO.extractValue(SourceFile:57)
        at com.milaboratory.mixcr.export.FieldWithParameters$create$2.invoke(SourceFile:583)
        at com.milaboratory.mixcr.export.FieldWithParameters$create$2.invoke(SourceFile:582)
        at com.milaboratory.o.lX.a(SourceFile:25)
        at com.milaboratory.o.mL.put(SourceFile:40)
        at cc.redberry.pipe.CUtils.drain(CUtils.java:82)
        at cc.redberry.pipe.util.PipeExtensionsKt.drainToAndClose(PipeExtensions.kt:155)
        at com.milaboratory.mixcr.cli.CommandExportAlignments$Cmd.run1(SourceFile:169)
        at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run0(SourceFile:69)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-32(SourceFile:539)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.milaboratory.mixcr.cli.Main.execute(SourceFile:105)
        at com.milaboratory.mixcr.cli.Main.main(SourceFile:101)
        Suppressed: java.lang.IllegalStateException: random access primitivI blocks or primitivI reader not closed
                at com.milaboratory.o.EH.a(SourceFile:174)
                at com.milaboratory.o.EH.close(SourceFile:287)
                at com.milaboratory.o.je.close(SourceFile)
                at com.milaboratory.mixcr.cli.CommandExportAlignments$AlignmentsAndMetaInfo.close(SourceFile)
                at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseable.kt:64)
                at com.milaboratory.mixcr.cli.CommandExportAlignments$Cmd.run1(SourceFile:139)
                ... 13 more

**Comment by mizraelson** [comment] 2024-10-02 20:32
It seems that the issue is due to a bug when using the `--impute-germline-on-export` parameter. Could you try running the command without it? If possible, please share the .clna file with us at support@milaboratories.com, and I will take a look to address this potential bug.

**Comment by Z-YWJ** [comment] 2024-10-03 16:09
Thanks for your kindess response. **When I remove the `--impute-germline-on-export` paramter** the command run smoothly. But because my clna file is so large that I can email to you.

**Comment by mizraelson** [comment] 2024-10-04 02:08
If possible you can share the file via Google Drive or any other convenient way.

**Comment by Z-YWJ** [comment] 2024-10-04 09:51
Hello, due to some reason,  the original .clna file (about ~70G) is deleted, but I reserve the incomplete .clna file (about ~4.4 G) and you can download via the link `https://cloud.tsinghua.edu.cn/f/dcf7afedec2d457e8ad2/`

I hope this incompleted file can help you to address this question and imporve **MIXCR**, if not, you can contact to me and I will run again to obtain the original .clna file.

**Comment by mizraelson** [comment] 2024-10-04 21:19
Hi, what do you mean by incomplete?

**Comment by Z-YWJ** [comment] 2024-10-05 05:16
When I download the original file (about ~70G), the download was interrupted due to network issues, so I only get the incomplete .clna file (about ~4.4 G). And when I notice this, I have depleted the original file.

**Comment by mizraelson** [comment] 2024-10-07 20:47
Unfortunately the partially downloaded file is corrupted and can't be used. You can also share the raw FAST files and I will try and replicate the error.

**Comment by mizraelson** [comment] 2024-10-17 18:22
I am going to close it for now. Feel free to reopen if you keep facing the issue.

**Closed as completed by mizraelson** 2024-10-17 18:22 UTC
