### ISSUE TITLE
Comparison between replicates

### ISSUE THREAD

**Issue by ktroule** [milaboratory/mixcr#497] opened 2019-02-20 15:19 UTC
Hi

I'm starting to play with mixcr to test I can run it without problems and I would like few things to know whether you can give me some hints.

I have some RNA samples across four different conditions (3 biological replicates for each condition, 12 in total). 
I have input each sample independently.  
`java -Xmx20g -jar /home//Programs/mixcr-3.0.4/mixcr.jar analyze shotgun "$data""${fastq["$index"]}" "${saveMixcr["$index"]}" -s MusMusculus --starting-material rna --receptor-type xcr  --verbose`

First thing I notice is that the number of lines in the All clonotype files does not match the number of lines of the rest of clonotypes files.
```
   491 Analysis_1.clonotypes.ALL.txt
   127 Analysis_1.clonotypes.IGH.txt
   297 Analysis_1.clonotypes.IGK.txt
    18 Analysis_1.clonotypes.IGL.txt
    23 Analysis_1.clonotypes.TRA.txt
    30 Analysis_1.clonotypes.TRB.txt
    23 Analysis_1.clonotypes.TRD.txt
     1 Analysis_1.clonotypes.TRG.txt
```

Can you suggest a way to compare differences in clonotypes between different conditions?

Thanks for your help.

**Comment by dbolotin** [comment] 2019-02-21 07:49
The problem is in TRD/TRA files. Because of the TRA/TRD locus [structure](http://www.imgt.org/IMGTrepertoire/index.php?section=LocusGenes&repertoire=locus&species=human&group=TRA) it is hard to tell TRA from TRD TCRs because they both uses the same V and J genes. The only reliable method is by looking at C gene, but it is possible only with RNA and with certain sample preparation protocols that leave enough number of C gene letters (outside the primer sequence, which might introduce chimeric artifacts). Or, in case of RNA-Seq, only for alignments covering C gene region.

This will be fixed in 3.1 version by outputting single TRAD file instead of separate TRA and TRD.

For the comparison method between conditions, I suggest you look into recent paper by Pogorelyy _et al_ (@pogorely):
https://elifesciences.org/articles/33050
But I'am afraid RNA-Seq data can't give you enough quantitative information to find the difference (unless it is RNA-Seq from sorted lymphocyte populations).

**Comment by ktroule** [comment] 2019-02-21 09:13
Thanks, I'll check the paper.

Thanks for your help.

**Comment by ktroule** [comment] 2019-02-21 11:51
To create the table that serves as input for the vdjRec tool identical CDR3 from different VJ combinations must be separated to perform the analysis. Wont you have a script to convert mixcr output to vdjRec input (as if not wrong both tools come from same lab).

Once more, thanks for your help,

**Comment by dbolotin** [comment] 2019-04-08 14:09
Sorry, unfortunately we don't have such script. To separate clonotypes by V/J genes please use `-OseparateByV=true` (see [here](https://mixcr.readthedocs.io/en/master/assemble.html#separation-of-clones-with-same-cdr3-clonal-sequence-but-different-v-j-c-genes)).

**Closed by dbolotin** 2019-04-08 14:09 UTC
Labels: question
