### ISSUE TITLE
incomplete IgH (D-J) alignment

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#209] opened 2017-02-13 05:53 UTC
we are going to use multiplex PCR protocol to detect incomplete IgH(D-J) and by Illumina Hiseq 150*2 in B-ALL patients. Since we are amplifying BCR (DNA) without V segment, can I still use MiXCR to process the data? If yes, which parameters I must use in the alignment?

Thank you very much!

**Comment by dbolotin** [comment] 2017-02-13 11:35
Hi,

Currently this is not possible.

However, we are working in this direction, and most probably this will be available in 2.2 release. Please follow this issue #32 .

I'll send you preview version by email, as soon as it will be available. What you asked in the previous issue, will also be possible #160 . If you can share your data, it will really help us to optimise this functionality.

Best,
Dmitry.

**Comment by suntaosimon** [comment] 2017-02-14 01:44
Thanks Dmitry, hope everything goes well. Yes, I can share my data once it has been processed.

**Comment by dbolotin** [comment] 2017-02-14 11:04
Great. Closing this issue as duplicate of #32. Please contact me by email as soon as you will be ready to share the data. We plan to write first code in this direction at the end of this week.

**Closed by dbolotin** 2017-02-14 11:04 UTC

**Comment by suntaosimon** [comment] 2018-07-31 04:54
@dbolotin How is the new version going about those functions?  
Best,

**Comment by dbolotin** [comment] 2018-07-31 09:19
Hi, implementation of this functionality was moved to 2.3.
