### ISSUE TITLE
mixcr assemblePartial issue

### ISSUE THREAD

**Issue by yingzhang121** [milaboratory/mixcr#323] opened 2018-01-18 18:52 UTC
Hi, developer,

Here is my command: mixcr assemblePartial aln.vdjca aln_rescued_1.vdjca
Below is the error message:
Building index: 0%
Building index: 13%  ETA: 00:00:13
Building index: 28.5%  ETA: 00:00:09
Building index: 43.1%  ETA: 00:00:07
Building index: 59.7%  ETA: 00:00:04
Building index: 76.6%  ETA: 00:00:02
Building index: 91.4%  ETA: 00:00:01
Searching for overlaps: 0%
Exception in thread "main" java.lang.IllegalArgumentException
	at com.milaboratory.mixcr.basictypes.VDJCAlignments.mergeOriginalReads(VDJCAlignments.java:86)
	at com.milaboratory.mixcr.partialassembler.TargetMerger.merge(TargetMerger.java:114)
	at com.milaboratory.mixcr.partialassembler.PartialAlignmentsAssembler.searchOverlaps(PartialAlignmentsAssembler.java:367)
	at com.milaboratory.mixcr.partialassembler.PartialAlignmentsAssembler.searchOverlaps(PartialAlignmentsAssembler.java:127)
	at com.milaboratory.mixcr.cli.ActionAssemblePartialAlignments.go(ActionAssemblePartialAlignments.java:62)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:155)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:115)

The message is so vogue for me to debug by myself. Could you shed some light?

Best,
- Ying

**Comment by PoslavskySV** [comment] 2018-01-18 19:01
Which version of MiXCR? Could you please confirm this bug with the most recent version (there were quite many bug fixes recently)

**Comment by PoslavskySV** [comment] 2018-01-18 19:09
As I see you use development version; I confirm this is a bug. Will fix it soon.

**Comment by dbolotin** [comment] 2018-01-19 11:00
Can you confirm that `aln.vdjca` file is not a result of merging of several other `.vdjca` files? Please post full pipeline you used to produce this file.

Please also try reproduce it (starting from raw data) with the latest stable version (2.1.8), and confirm that the same error is observed.

Thanks!

**Comment by yingzhang121** [comment] 2018-01-19 16:52
Sorry that I couldn't go back to you earlier. I was busy fixing my NCBI genome submission (still not done).

Here is all my commands (so far)
mixcr align -p rna-seq -OallowPartialAlignments=true -f --library imgt -s 9544 work/Amazo_D-4_S8_R1_001.fastq work/Amazo_D-4_S8_R2_001.fastq aln.vdjca
mixcr assemblePartial aln.vdjca aln_rescued_1.vdjca

If necessary, I could put the aln.vdjca file in a place where you can download it.

**Comment by yingzhang121** [comment] 2018-01-19 18:00
So far, the 2.1.8 version has passed the breakpoint.

$ mixcr.old align -p rna-seq -OallowPartialAlignments=true -f --library imgt -s 9544 work/Amazo_D-4_S8_R1_001.fastq work/Amazo_D-4_S8_R2_001.fastq aln.vdjca
Reference library: imgt.201802-5.sv2.1.7-14-gc6be856:9544:af752e185436b171b876d05083d5f8b8
WARNING: forcing -OvParameters.geneFeatureToAlign=VRegionWithP since current gene feature (VTranscriptWithout5UTRWithP) is absent in 100% of V genes.
WARNING: 2 functional genes were excluded, re-run with -v option to see the list of excluded genes and exclusion reason.
Alignment: 0.1%
Alignment: 10.8%  ETA: 00:01:47
Alignment: 21.7%  ETA: 00:01:40
Alignment: 32.3%  ETA: 00:01:29
Alignment: 43.3%  ETA: 00:00:56
Alignment: 54.2%  ETA: 00:00:42
Alignment: 65%  ETA: 00:00:32
Alignment: 75.8%  ETA: 00:00:22
Alignment: 86.3%  ETA: 00:00:13
Alignment: 97.3%  ETA: 00:00:02
============= Report ==============
Analysis time: 1.76m
Total sequencing reads: 1526614
Successfully aligned reads: 755493 (49.49%)
Paired-end alignment conflicts eliminated: 142718 (9.35%)
Alignment failed, no hits (not TCR/IG?): 721090 (47.23%)
Alignment failed because of absence of CDR3 parts: 10465 (0.69%)
Alignment failed because of low total score: 39566 (2.59%)
Overlapped: 958012 (62.75%)
Overlapped and aligned: 532950 (34.91%)
Alignment-aided overlaps: 31704 (5.95%)
Overlapped and not aligned: 425062 (27.84%)

$ mixcr.old assemblePartial aln.vdjca aln_rescued_1.vdjca
Building index: 0%
Building index: 17.4%  ETA: 00:00:09
Building index: 28%  ETA: 00:00:06
Building index: 38.9%  ETA: 00:00:05
Building index: 58.3%  ETA: 00:00:04
Building index: 68.9%  ETA: 00:00:02
Building index: 79.9%  ETA: 00:00:01
Building index: 100%  ETA: 00:00:00
Searching for overlaps: 0%
Searching for overlaps: 0.7%  ETA: 04:54:44
Searching for overlaps: 1.1%  ETA: 07:20:12
Searching for overlaps: 1.7%  ETA: 05:50:09

**Comment by PoslavskySV** [comment] 2018-01-19 18:04
@dbolotin bug was introduced in the develop branch (after refactoring of `VDJCAlignments`)

**Comment by dbolotin** [comment] 2018-01-19 22:31
Overall, this seems to be ok, this functionality is not finished yet.

Please use stable MiXCR releases. We release new features as soon as they are ready, so there is no much reason to use development versions for "production" data analysis.

Anyway, thanks for reporting! I will leave this opened, until this will be fixed in `develop`.

**Comment by yingzhang121** [comment] 2018-01-20 05:28
@dbolotin , thank you. I did realize that I pulled the develop branch after I couldn't make mixcr work out of box. But I "thought" I could resolve the issues, so I didn't switch to "master" timely.  Will only work with stable release in the future.

**Comment by anabteles** [comment] 2018-03-19 12:06
Hi, 
I am having a problem while trying to align my reads with zebrafish sequences. It seems that mixcr is not recognizing the external library. 
I ve put the imgt.201748-3.sv2.json file in the /libraries folder but the message I get while writing the command: "!java -Xmx8G -jar ./mixcr-2.1.9/mixcr.jar -v"
is:
- built-in libraries
- Z:\TCRseq\L001_L002_together\.

MiXCR v2.1.9 (built Tue Feb 06 23:28:21 CET 2018; rev=7b576eb; branch=hotfix/v2.1.9)
RepSeq.IO v1.2.11 (rev=de00211)
MiLib v1.8.2 (rev=50b6731)
Built-in V/D/J/C library: repseqio.v1.5

Library search path:


With no item at all writen in the search path...

Do you have any suggestions?
Thanks in advance,
Ana

**Closed** 2018-07-16 15:14 UTC
Labels: bug
