### ISSUE TITLE
Why TRA will appear with TRD

### ISSUE THREAD

**Issue by qtwwthx** [milaboratory/mixcr#434] opened 2018-10-10 06:55 UTC
This is my command：
mixcr align -p rna-seq -OallowPartialAlignments=true -OvParameters.geneFeatureToAlign=VTranscript  SRR4296${i}_1.fastq.gz  SRR4296${i}_2.fastq.gz SRR4296${i}_paired.vdjca
mixcr assemblePartial  SRR4296${i}_paired.vdjca SRR4296${i}_paired_rescued_1.vdjca 
mixcr assemblePartial  SRR4296${i}_paired_rescued_1.vdjca  SRR4296${i}_paired_rescued_2.vdjca 
mixcr extendAlignments  SRR4296${i}_paired_rescued_2.vdjca SRR4296${i}_paired_rescued_2_extended.vdjca 
mixcr assemble -ObadQualityThreshold=0 SRR4296${i}_paired_rescued_2_extended.vdjca SRR4296${i}_paired_rescued_2_extended.clns 
mixcr exportClones -c TRD SRR4296${i}_paired_rescued_2_extended.clns SRR4296${i}_paired_rescued_2_extended.clns.txt
I  want to I want to analyze RNA-seq data，and extract the TCR's TRD chain. But TRA will appear with TRD. What is the reason?

**Comment by qtwwthx** [comment] 2018-11-08 07:34
Plesae? Thank you!

**Comment by PoslavskySV** [comment] 2018-11-08 08:47
Duplicate of #449

**Closed by PoslavskySV** 2018-11-08 08:47 UTC

**Comment by PoslavskySV** [comment] 2018-11-08 08:50
@qtwwthx BTW if you want that your questions be answered faster, post them according to the issue template, carefully fill all required sections and provide the link to the problematic fastq reads. Otherwise there is a small probability that your question will be considered. PS  look [GitHub Markdown](https://guides.github.com/features/mastering-markdown/) guide on how to format the code,.
