### ISSUE TITLE
v2.1.5: Incorrect total sequencing number in align report file

### ISSUE THREAD

**Issue by xww52526** [milaboratory/mixcr#276] opened 2017-11-15 17:57 UTC
Hello,

I've used v1.7.1 and started using v2.1.5. I found that in alignment report file generated by v2.1.5, the "Total sequencing reads" number was incorrect sometimes. It is supposed to match reads number in the original fastq files; but the reporting number sometimes more than reads in fastq; whilst in v1.7.1 "Total sequencing reads" always match what's in FASTQs.
Is this a bug? Or definition of "Total sequencing reads" changed? I'm using paired-end FASTQs, is it possible same reads were counted twice in v2.1.5?

I've attached an example, align command I used:
align -c TCR -s hsa JurkatRNA_R6_C12_Jurkat-98010_S1_L001_R1_001.fastq JurkatRNA_R6_C12_Jurkat-98010_S1_L001_R2_001.fastq JurkatRNA_R6_C12-AGTAATAACC.vdjca --report JurkatRNA_R6_C12-AGTAATAACC_align_report.txt

Thanks,
Wendy

I changed .fastq to .fastq.txt so that they could be attached here.
[JurkatRNA_R6_C12-AGTAATAACC_align_report.txt](https://github.com/milaboratory/mixcr/files/1475788/JurkatRNA_R6_C12-AGTAATAACC_align_report.txt)
[JurkatRNA_R6_C12_Jurkat-98010_S1_L001_R1_001.fastq.txt](https://github.com/milaboratory/mixcr/files/1475789/JurkatRNA_R6_C12_Jurkat-98010_S1_L001_R1_001.fastq.txt)
[JurkatRNA_R6_C12_Jurkat-98010_S1_L001_R2_001.fastq.txt](https://github.com/milaboratory/mixcr/files/1475790/JurkatRNA_R6_C12_Jurkat-98010_S1_L001_R2_001.fastq.txt)

**Comment by dbolotin** [comment] 2017-11-15 21:33
Yes, this is a known bug (duplicate of #265). Thanks for reporting! It will be fixed in the next release.

**Comment by xww52526** [comment] 2017-11-15 23:24
Thanks! Do you have estimate for the next release date?

**Comment by PoslavskySV** [comment] 2017-11-21 16:08
@xww52526 the next bugfix release is planned on next two weeks

**Closed** 2017-11-22 14:16 UTC
Labels: duplicate
