### ISSUE TITLE
Feature Request: Propagate Deviation from Germline

### ISSUE THREAD

**Issue by iansetliff** [milaboratory/mixcr#236] opened 2017-04-24 00:15 UTC
If I understand things right, only sequence information for the clonal sequence is used in the assemble step, with no other nitty-gritty details passed on down the pipeline other than V&J assignment and such (ie mutation information is not in the clones object unless it's part of the clonal sequence). It would be nice if we could still define clones based on just CDR3 sequence, ie default, but also pass how mutated the V region is to next steps. As far as I know, the only way to capture this information is to expand the clonal sequence used in the assembly step.

Thanks!

**Comment by mikessh** [comment] 2017-04-24 01:02
You mean to generate an output like

```
100 CAWRNGENEKLFF IGHV4 S12:G>A(70/100);S40:T>C(20/100);... 
overall 230 mutations per 100 cells x 600bp
```

for a sample that have 100 cells sharing ``CAWRNGENEKLFF`` CDR3 (on the nucleotide level of course). Do I get this right?

**Comment by iansetliff** [comment] 2017-04-24 01:37
That could be useful, but, now that I think about it (and sorry for just now coming up with this), an alternative could be to just have the ability to retrieve all sequences with a given CDR3 from the first available nucleotide, or define clonal sequence from first available nucleotide. Basically, I'm thinking for characterizing SHM (ie vBestIdentityPercent for 1stAvailableNucleotide:FW3, ), etc. 

If using biomed-2, which sit somewhere in FW1, we can start the clonal sequence from CDR1 (for example), count mutations, and normalize by # nucleotides from CDR1:FW3 for a "% deviation from germline", but we may miss mutations from FW1 between first available nucleotide and end of FW1. Does that make sense?

**Comment by dbolotin** [comment] 2017-04-28 07:57
What about extracting `-nMutations` for something like `'{CDR1Begin(-15):FR3End}'`, -15 here is absolutely arbitrary (!), but there must be an offset value that includes substantial part of FR1 and still not covers primer nucleotides (if you calculate the value for BIOMED-2 I will be happy to add it to the docs, this seems to be a useful information for analysis).
To include this part of the sequence into clonal sequence you can also use the same offset on the assembling stage:
```
mixcr assemble -OassemblingFeatures='{CDR1Begin(-15):CDR3End}' ...
```
I also suggest looking at `-mutationsDetailed` column, by utilising the information from it, you will be able to distinguish between sense and non-sense mutations, which might be interesting in the context of SHMs.

**Comment by PoslavskySV** [comment] 2017-11-21 16:32
Duplicate of #263 and #13

**Closed** 2017-11-21 16:33 UTC
Labels: duplicate
