### ISSUE TITLE
Retrieve consensus sequence associated to Clone Count

### ISSUE THREAD

**Issue by adbondt** [milaboratory/mixcr#167] opened 2016-11-03 13:09 UTC
During assembly, when using the default -OassemblingFeatures, only the CDR3 region is exported as Clonal sequence.
When using -OassemblingFeatures ="[FR3,CDR3,FR4]", the clone counts drop more than 100 fold or the clones are often not retrieved anymore.
Therefor this question: how to, based on TCR amplicon seq data (cf. https://www.ncbi.nlm.nih.gov/pubmed/24952902), retrieve, per sample, the consensus sequence of the whole sequenced amplicons (3' part of FR3, CDR3 and 5' part of FR4)?

Thanks in advance!

**Comment by dbolotin** [comment] 2016-11-07 21:36
Hello,

We are currently actively thinking on adding a special action to assemble maximally possible contig sequence for clones. But in current version, and in 2.1.0 this feature will not be available. For now you can try to assemble clonotypes using CDR3 sequence with some fixed offsets (try different values to achieve best extraction percent):

```
-OassemblingFeatures ='CDR3(-15,+15)'
```

Notice single-quotes (with double-quotes bash will interpret brackets as code).

I also recommend to take a look at several raw alignments to get the idea of actual library structure (actual positions of CDR3 region, distribution of quality across the read, any artefacts) :

```
mixcr exportAlignmentsPretty -s 10000 -n 10 alignments.vdjca
```

This will skip first 10,000 alignments (first sequences in fastq files often has low quality and artefacts) and print 10 alignments to console.

**Comment by adbondt** [comment] 2016-11-08 08:30
Thanks a lot for your work.

While that functionality is not yet available, could we also do the following:
1. retrieve the target
2. check the mutations to the target seq and adjust these in the retrieved target

cf. http://mixcr.readthedocs.io/en/latest/appendix.html#alignment-and-mutations-encoding

**Comment by PoslavskySV** [comment] 2017-11-21 16:49
Duplicate of #263

**Closed by PoslavskySV** 2017-11-21 16:49 UTC
Labels: duplicate
