### ISSUE TITLE
License Validity

### ISSUE THREAD

**Issue by kopardev** [milaboratory/mixcr#922] opened 2022-12-13 15:11 UTC
## Checklist before submitting the issue:

 - [x] The issue is strongly related to the MiXCR software
 - [x] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [x] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

file `Test3_R_T.aln.vdjca`

## Actual Result

`  License error: WrongValidityPeriod: License expired`

## Exact MiXCR commands 

```
mixcr -e MI_LICENSE_FILE=../mi.license align -t 1 -p rna-seq -s hsa -OallowPartialAlignments=true --report Test3_R_T.alignment.log ../Test3_R_T_R1.trim.fastq.gz ../Test3_R_T_R2.trim.fastq.gz Test3_R_T.aln.vdjca
```

## MiXCR report files 

- No reports were generated
- files `../mi.license align` `../Test3_R_T_R1.trim.fastq.gz` `../Test3_R_T_R2.trim.fastq.gz` are all readable.
- execution folder is writable.

**Comment by PoslavskySV** [comment] 2022-12-13 15:14
Hi Vishal,

you current academic license is valid till Dec 2023. Do you have internet access on the machines running MiXCR? It requires internet access to periodically validate the license. If your machines are offline, I'll provide you instructions how to setup this.

Best,
Stan

**Comment by kopardev** [comment] 2022-12-13 15:38
I was able to get around the issue ... problem was that environmental variable was not getting correctly defined for the MI_LICENSE_FILE. Now I am running into a new issue: 
```
No preset with name "rnaseq-full-length"
```
The complete command is 
```
mixcr analyze rnaseq-full-length --species hsa ../Test3_R_T_R1.trim.fastq.gz ../Test3_R_T_R2.trim.fastq.gz Test3_R_T.aln.vdjca
```

**Comment by PoslavskySV** [comment] 2022-12-13 15:42
Hi,

it seems that you use version before 4.1.2. There was an issue with naming of this preset, it was called `rnaseq-tcr-full-length` (disregard "tcr"). 

Also I see another issue with your command: you use `mixcr analyze` but specify `Test3_R_T.aln.vdjca` as output prefix. The correct `mixcr analyze` command will be (disregard "tcr"):

```
mixcr analyze rnaseq-tcr-full-length --species hsa ../Test3_R_T_R1.trim.fastq.gz ../Test3_R_T_R2.trim.fastq.gz Test3_R_T
```

Or if you update to MiXCR 4.1.2:

```
mixcr analyze rnaseq-full-length --species hsa ../Test3_R_T_R1.trim.fastq.gz ../Test3_R_T_R2.trim.fastq.gz Test3_R_T
```

**Comment by PoslavskySV** [comment] 2022-12-13 15:43
Please, let me know whether it will work.

**Comment by kopardev** [comment] 2022-12-13 16:12
@PoslavskySV Thanks for your prompt responses. I really appreciate them. I will try to make these changes and report back. Just FYI....
```bash
% mixcr --version
MiXCR v4.1.0 (built Tue Oct 18 13:33:21 EDT 2022; rev=852d9d8feb; branch=no_branch; host=fv-az200-293)
RepSeq.IO v1.5.0 (rev=6e9d72efb7)
MiLib v2.1.0 (rev=2142a7fa5a)
Built-in V/D/J/C library: repseqio.v2.0
```

**Comment by PoslavskySV** [comment] 2022-12-21 16:16
Closing this at the moment. Feel free to reopen if the problem persists.

**Closed as completed by PoslavskySV** 2022-12-21 16:16 UTC

**Comment by vinegang** [comment] 2023-01-02 13:39
@PoslavskySV I work with @kopardev. Last week we noticed these license expired errors. We do have internet access on the machine . Could you please help us understand the cause for this. [mixcr CCRGeneticsBranch/AWS_POC_Nextflow/issues/4](https://github.com/CCRGeneticsBranch/AWS_POC_Nextflow/issues/4#issuecomment-1366956841)

Thanks,
Vineela

**Comment by PoslavskySV** [comment] 2023-01-02 13:46
Hi, thank you for reaching us. Please, provide user name and email used to obtain license. If you prefer, you can send this information to us to support@milaboratories.com

**Comment by PoslavskySV** [comment] 2023-01-02 17:05
@vinegang Can you try to update to MiXCR v4.1.2 ?
